### ISSUE TITLE
Error - Script function not found: FunctionGWcodersSchedule

### ISSUE THREAD

**Issue by Model-Lab-Net** [ryanrwatkins/Google-Sheet-to-Calendar#1]
Hello. Can you can assist me with this error.
What am I doing wrong?

**Comment by CaitanyaCandra** [comment]
change line 5 to:
      .addItem('Update Calendar', 'schedule')

presuming that line 9 stays:
    function schedule() {

**Comment by ryanrwatkins** [comment]
@CaitanyaCandra 
Thanks! I have updated the script.  Somehow I missed the issue being posted back in Sept.
